name: Run Robot Framework Tests

on:
    push:
        branches:
            - master
        paths:
            - "**.robot"
            - "**.py"
            - "requirements.txt"
    pull_request:
        branches:
            - master
jobs:
    robot-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  python -m webdrivermanager chrome --linkpath /usr/local/bin

            - name: Run Robot Framework tests
              run: |
                  robot simple.robot
